- problems/string-length/problem.md
"Thing" becoming "the" is a grammar fix.
About the string assignment sentence being changed a second time:  I can't believe I did that word ordering!  Technically, the grammatical structure was telling JavaScript adventurers to do this number:
```
'example string' = example;
```
Very sorry about that!  In my defense, it was rather late at night when I did it.
> A couple of minor grammatical fixes.

- problems/for-loop/problem.md
The text for the for-loop problem may be a little unclear. For example, it says to have the loop run 10 times but it does not say whether the counter will go from 0 to 9 or 1 to 10. The latter will end up with the wrong result (55 instead of 45). I've tried to clarify things a little bit.
> revise for-loop text

- run-solution.js
> Fixed a bug with the exec command with paths containing spaces

- problems/for-loop/problem.md
- problems/function-arguments/problem.md
- problems/functions/problem.md
- problems/numbers/problem.md
- problems/rounding-numbers/problem.md
- problems/string-length/problem.md
Some minor markup/whitespace fixes.
> Minor markup fixes.

- problems/if-statement/problem.md
- problems/number-to-string/problem.md
- problems/string-length/problem.md
- problems/strings/problem.md
- problems/variables/problem.md
Added the challenge and note word to some exercises To diference the info.
> Added words.

- problems/revising-strings/problem.md
Maybe just me and my monitor's contrast, but I thought the desired string was 'pizza is alright.' when I ran through this exercise. I was debating moving the period into the string, but figured this might be more clear.
Also removed one trailing whitespace.
Please feel free to tell me this is pointless and that most people should notice the color difference :smiley:, or if you have a better suggestion!
> Remove possibly confusing period.

- problems/function-arguments/problem.md
Just going through the paces with javascripting. I found this problem fine, but thought it was not as obvious as it could be. What do you think about place arguments in back ticks to make them more obvious.
> Update functional-argumets description

- index.js
- package.json
Switched javascripting to workshopper-adventure for testing workshopper before the next PR :smile:
> Switched to workshopper :-O

- problems/scope/problem_es.md
- problems/scope/solution_es.md
Hi @sethvincent, this is the Spanish translation for scope challenge.
Thanks!
> add spanish translation for scope

- problems/accessing-array-values/problem_es.md
- problems/array-filtering/problem_es.md
- problems/arrays/problem_es.md
- problems/for-loop/problem_es.md
- problems/function-arguments/problem_es.md
- problems/functions/problem_es.md
- problems/if-statement/problem_es.md
- problems/introduction/problem_es.md
- problems/looping-through-arrays/problem_es.md
- problems/number-to-string/problem_es.md
- problems/numbers/problem_es.md
- problems/object-properties/problem_es.md
- problems/objects/problem_es.md
- problems/revising-strings/problem_es.md
- problems/rounding-numbers/problem_es.md
- problems/string-length/problem_es.md
- problems/strings/problem_es.md
- problems/variables/problem_es.md
I've changed the challenges section of every exercise, the user must write the solution in english for the verification to be successful, so if we provide spanish examples the user will write it in spanish too, and it will fail in the verification step.
> Changes made to the challenges in spanish.

- problems/scope/problem.md
> a minor typo

- package.json
Updated the reference in the dependencies.
> There is a workshopper-adventure now published.

- problems/scope/problem.md
Hi, finished the exercises (great tutorial) and noticed that the final Scope.md problem was missing the verify step that was there for all the other exercises.  Figured I'd submit a PR - I'm new to this so hopefully this is OK.  Thanks!
> Added verify step at end of scope.md exercise

- i18n/troubleshooting_pt-br.md
- problems/function-arguments/problem_pt-br.md
- problems/introduction/problem_pt-br.md
- problems/introduction/solution_pt-br.md
- problems/object-properties/problem_pt-br.md
The title says it all. :smiley:
> Fixing a little bit typos from pt-br translation.

- i18n/pt-br.json
I'm revisioning pt-BR translation. Everything seems to be right, just fixing some simple errors.
Right now, I'm looking for new errors, please don't merge it yet...
> pt-BR translation revision

- problems/arrays/problem_ja.md
I found the unnecessary character in `problems/arrays/problem_ja.md`.
So that was put out.
> unnecessary character in arrays/problem_ja

- problems/numbers/problem_es.md
I am doing the whole workshopper in Spanish, I will correct any mistake encountered.  It is fine to create a PR for each one or just one PR for all errors?
Thanks!
> Spanish typo in number exercise

- problems/objects/problem.md
Added semicolons to the end of each object variable in the problem.md file for the objects tutorial, as they are missing.
> Added ; to the end of both object declarations

- problems/introduction/problem.md
This was in answer to https://github.com/nodeschool/discussions/issues/1337. 
Thoughts?
> Added a note about changing the file names and verifying them

- problems/rounding-numbers/problem.md
As someone unfamiliar with JavaScript, it wasn't immediately obvious how `Math.round()` worked.
> Function Clarification

- problems/function-arguments/problem.md
The challenge for this problem is jarring compared to the `Functions` problem which came before it. It wasn't obvious to me that the equation could be in the return statement, so my code ended up being overly verbose because I had to just guess a solution:
```javascript
function math (firstArg, secondArg, thirdArg) {
var argValue = secondArg * thirdArg + firstArg;
return argValue;
}
console.log(math (53, 61, 67));
```
> Better Phrasing for the Challenge

- problems/numbers/problem_pt-br.md
> Corrigindo um título do desafio 6 (numbers)

- problems/introduction/problem.md
The sentence "you can name give the file you work with any name you like" is trying to both be
> you can give the file you work with any name you like
And 
> you can name the file you work with anything you like
While both are valid in theory, in-reality we do need to actually pick one. I went with the former.
> Schrodinger's sentence structure

- problems/numbers/problem.md
I've noticed this little typo while doing the workshop, have added the word have to the sentence.
> adding missing word in problems/numbers/problem.md

- problems/for-loop/problem.md
> Clarified what is going on inside a for-loop

- problems/if-statement/solution_es.md
- problems/string-length/solution_es.md
String must not be translated because test is based on 'example string'
> ES Translation error

- problems/for-loop/problem_es.md
> Wrong file name

- lib/compare-solution.js
- lib/problem.js
- lib/run-solution.js
- package.json
It is easy to forget that typing skills are highly variable across people not programming every day. When someone messes up the file name for one of the verify paths they are given a very scary message! Let's help people by providing a human message that is actionable without the help from someone who can understand the confusing error.
> Give a human error message when passed an invalid path.

- problems/introduction/problem.md
`Windows` is a proper noun so capitalize it.
> windows -> Windows

- problems/strings/problem.md
Definition of `string` was a little loose. This provides more information and precision.
> more precision in strings explanation

- CONTRIBUTING.md
Also made a few grammatical fixes to the opening paragraph.
> Added link to Javascripting team page

- problems/array-filtering/problem.md
Whether or not this line is needed depends on how much hand-holding we want this problem to have.
> Clarification

- LOCALIZING.md
Helps translators contribute voluntary translations as discussed in #76.
> Adds a howto to localize the workshopper to new languages

- problems/accessing-array-values/problem.md
- problems/accessing-array-values/problem_es.md
- problems/accessing-array-values/problem_fr.md
- problems/accessing-array-values/problem_it.md
- problems/accessing-array-values/problem_ja.md
- problems/accessing-array-values/problem_ko.md
- problems/accessing-array-values/problem_nb-no.md
- problems/accessing-array-values/problem_pt-br.md
- problems/accessing-array-values/problem_ru.md
- problems/accessing-array-values/problem_uk.md
- problems/accessing-array-values/problem_zh-cn.md
- problems/accessing-array-values/problem_zh-tw.md
- solutions/accessing-array-values/index.js
Contributes to https://github.com/workshopper/javascripting/issues/212
> Replace var with const and let in accessing-array-values

- problems/objects/problem.md
- problems/objects/problem_es.md
- problems/objects/problem_fr.md
- problems/objects/problem_it.md
- problems/objects/problem_ja.md
- problems/objects/problem_ko.md
- problems/objects/problem_nb-no.md
- problems/objects/problem_pt-br.md
- problems/objects/problem_ru.md
- problems/objects/problem_uk.md
- problems/objects/problem_zh-cn.md
- problems/objects/problem_zh-tw.md
- solutions/objects/index.js
> Updating objects to use const instead of var

- problems/object-properties/problem.md
- problems/object-properties/problem_es.md
- problems/object-properties/problem_fr.md
- problems/object-properties/problem_it.md
- problems/object-properties/problem_ja.md
- problems/object-properties/problem_ko.md
- problems/object-properties/problem_nb-no.md
- problems/object-properties/problem_pt-br.md
- problems/object-properties/problem_ru.md
- problems/object-properties/problem_uk.md
- problems/object-properties/problem_zh-cn.md
- problems/object-properties/problem_zh-tw.md
- solutions/object-properties/index.js
> Update object-properties to use const instead of var

- problems/revising-strings/problem.md
- problems/revising-strings/problem_es.md
- problems/revising-strings/problem_fr.md
- problems/revising-strings/problem_it.md
- problems/revising-strings/problem_ja.md
- problems/revising-strings/problem_ko.md
- problems/revising-strings/problem_nb-no.md
- problems/revising-strings/problem_pt-br.md
- problems/revising-strings/problem_ru.md
- problems/revising-strings/problem_uk.md
- problems/revising-strings/problem_zh-cn.md
- problems/revising-strings/problem_zh-tw.md
- solutions/revising-strings/index.js
> Update revising-strings to use let instead of var

- problems/string-length/problem.md
- problems/string-length/problem_es.md
- problems/string-length/problem_fr.md
- problems/string-length/problem_it.md
- problems/string-length/problem_ja.md
- problems/string-length/problem_ko.md
- problems/string-length/problem_nb-no.md
- problems/string-length/problem_pt-br.md
- problems/string-length/problem_ru.md
- problems/string-length/problem_uk.md
- problems/string-length/problem_zh-cn.md
- problems/string-length/problem_zh-tw.md
- solutions/string-length/index.js
> Update string-length to use const instead of var

- problems/array-filtering/problem.md
- problems/array-filtering/problem_es.md
- problems/array-filtering/problem_fr.md
- problems/array-filtering/problem_it.md
- problems/array-filtering/problem_ja.md
- problems/array-filtering/problem_ko.md
- problems/array-filtering/problem_nb-no.md
- problems/array-filtering/problem_pt-br.md
- problems/array-filtering/problem_ru.md
- problems/array-filtering/problem_uk.md
- problems/array-filtering/problem_zh-cn.md
- problems/array-filtering/problem_zh-tw.md
- solutions/array-filtering/index.js
> fix: 'var' to 'const' in array-filtering

- solutions/if-statement/index.js
> fix: 'var' to 'const' in if-statement solution

- problems/looping-through-arrays/problem.md
- problems/looping-through-arrays/problem_es.md
- problems/looping-through-arrays/problem_fr.md
- problems/looping-through-arrays/problem_it.md
- problems/looping-through-arrays/problem_ja.md
- problems/looping-through-arrays/problem_ko.md
- problems/looping-through-arrays/problem_nb-no.md
- problems/looping-through-arrays/problem_pt-br.md
- problems/looping-through-arrays/problem_ru.md
- problems/looping-through-arrays/problem_uk.md
- problems/looping-through-arrays/problem_zh-cn.md
- problems/looping-through-arrays/problem_zh-tw.md
- solutions/looping-through-arrays/index.js
> fix: 'var' to 'let' & 'const' in looping-through-arrays

- problems/strings/problem.md
- problems/strings/problem_es.md
- problems/strings/problem_fr.md
- problems/strings/problem_it.md
- problems/strings/problem_ja.md
- problems/strings/problem_ko.md
- problems/strings/problem_nb-no.md
- problems/strings/problem_pt-br.md
- problems/strings/problem_ru.md
- problems/strings/problem_uk.md
- problems/strings/problem_zh-cn.md
- problems/strings/problem_zh-tw.md
Reverts workshopper/javascripting#248
This was accidentally merged to master
> Revert "changes var to const in strings"

- solutions/rounding-numbers/index.js
contribution to issue https://github.com/workshopper/javascripting/issues/229
// for es6 branch @AnshulMalik
> changes var to const in rounding-numbers

- problems/number-to-string/problem_zh-cn.md
n is not a constant, hence we should use 'let' in this case.
> Use "let".

- problems/for-loop/problem.md
Hey all.
I wrote up this light-hearted extra paragraph to be added after the code block with `total += i;` for some extra information.  I tried to explain the for loop here in simple terms that hopefully didn't spoil too much of the exercise.  Comments appreciated.
Fixes: https://github.com/workshopper/javascripting/issues/220
https://github.com/workshopper/javascripting/issues/209
https://github.com/workshopper/javascripting/issues/150
> clarify for-loop challenge wording to fix #220

- i18n/es.json
- problems/object-keys/problem_es.md
- problems/object-keys/solution_es.md
* Adds translation of `OBJECT KEYS` in `i18n/es.json`
* Adds translation of `problems/object-keys/problem.md` in `problems/object-keys/problem_es.md`
* Adds translation of `problems/object-keys/solution.md` in `problems/object-keys/solution_es.md`
> Adds spanish translation for object-keys exercise #267

- problems/object-keys/problem_es.md
A little improvements in spanish translation.
> docs(object-keys): improve spanish translation

- README.md
- TROUBLESHOOTING.md
This is an attempt to improve README.
I removed some reference to old node versions and moved installation troubleshooting to an own file for troubleshooting.
Let me know your thoughts.
> docs: update README

- lib/compare-solution.js
- lib/get-file.js
- lib/problem.js
- lib/run-solution.js
- package.json
- solutions/scope/index.js
Just a few straggler issues that weren't automatically fixed. Now the tests pass :)
> Fix remaining StandardJS errors

- .github/ISSUE_TEMPLATE/new-challenge-proposal.md
Continuing with #282 , this is a template for new challenge proposals.
> add new challenge template

- i18n/pt-br.json
- problems/object-keys/problem_pt-br.md
- problems/object-keys/solution_pt-br.md
Add PT-BR translation of OBJECT-KEYS.
Adicionada Tradução PT-BR de OBJECT-KEYS.
> Add PT-BR translation of OBJECT-KEYS

- problems/if-statement/problem_pt-br.md
Fix portuguese confusing translation problem. Issue  #206 
Corrigida tradução confusa em português para o problema.
> Fix portuguese confusing translation problem

- i18n/fr.json
- problems/object-keys/problem_fr.md
- problems/object-keys/solution_fr.md
* Adds translation of OBJECT KEYS in i18n/fr.json
* Adds translation of problems/object-keys/problem.md in problems/object-keys/problem_fr.md
* Adds translation of problems/object-keys/solution.md in problems/object-keys/solution_fr.md
>  Adds french translation for object-keys exercise workshopper#267

- .travis.yml
Aside config file, we need to activate repository in travis
> chore: add travis config

- .workshopper-test.config.js
- package-lock.json
- package.json
This PR is an attempt to add `workshopper-adventure-test` for verify solutions, like commented in #281.
This is using feature branches for workshopper/workshopper-adventure-test#33 and workshopper/workshopper-adventure#107, since that changes are needed for load exercises correctly. But would be great if someone can help review that PRs in order to get merged.
> add workshopper-adventure-test

- solutions/object-keys/index.js
Fixes Exercise 17 (OBJECT KEYS) solution
I think the solution of Exercise 17 (OBJECT KEYS) is incorrect. So I fixed it.
The correct solution should be:
``` js
const car = {
make: 'Honda',
model: 'Accord',
year: 2020
}
const keys = Object.keys(car)
console.log(keys)
```
But now it gives:
``` js
const car = {
make: 'Toyota',
model: 'Camry',
year: 2020
}
const keys = Object.keys(car)
console.log(keys)
```
> Fixes object-keys solution

- problems/object-keys/problem_ja.md
- problems/object-keys/solution_ja.md
The content of object-keys(problem_ja.md, solution_ja.md) was not translated into Japanese, so I translated it into Japanese.
> Added Japanese translation for content of object-keys

- TROUBLESHOOTING.md
After #301 & #303 figured it would be helpful to add the Node.js version info to our Troubleshooting docs.
> Add node.js version info
